config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :rooms do
    resources :messages
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users
  has_many :messages

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    root_path
  end

  def after_sign_in_path_for(resource)
    rooms_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path
    else
      render :new
    end
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/homes/top.html.erb
<div class='top-box' id='top'>
  <header class='top-header'>
      <%= link_to 'CHAT CHAT', rooms_path, class:"title-chat" %>
    <div class='nav'>
      <ul class='top-lists'>
        <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, "#", class: "user-nickname"%></li>
        <li><%= link_to 'logout', destroy_user_session_path, method: :delete, class: "logout"%></li> 
        <% else %>
        <li><%= link_to 'login', user_session_path, class: "login"%></li>
        <li><%= link_to 'sign-up', new_user_registration_path, class: "sign-up"%></li>
        <% end %>
      </ul>
    </div>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatchat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= message.user.nickname %>
    </div>
    <div class="message-date">
      <%= l message.created_at, format: :short %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= message.content %>
    </div>
  </div>
</div>

app/views/messages/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <div class='side-bar-header'>
      <div class="header-name">
         <a href="#">Tom</a>
      </div>
      <div class="create-room">
        <%= link_to "チャットを作成する", new_room_path %>
      </div>
    </div>

    <div class='side-bar-room'>
      <% current_user.rooms.each do |room| %>
        <div class="room">
          <div class="room-name">
            <%= link_to room.name, room_messages_path(room) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class='main-bar'>
    <div class='main-bar-header'>
      <div class="left-header">
        <div class="header-title">
          <%= @room.name %>
        </div>
      </div>
      <div class="right-header">
        <div class="header-button">
          <a href="#">チャットを終了する</a>
        </div>
      </div>
    </div>

    <div class='main-bar-chat'>
        <%= render partial: 'message', collection: @messages %>
    </div>
    <div class='main-bar-message'>
      <%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
        <div class="form-input">
          <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
          <label class="form-image">
            <span class="image-file">画像</span>
            <%= f.file_field :image, class: 'hidden' %>
          </label>
        </div>
        <%= f.submit '送信', class: 'form-submit' %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<%= render "shared/header" %>
  <div class="rooms-index">
  <% current_user.rooms.each do |room| %>
    <div class="room-index">
      <div class="room-name-index">
        <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
  </div>



<%= render "shared/footer" %>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
         <select name="room[user_ids][]" >
          <option value="">チャットするユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.nickname %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class='footer'>
  <p>© CHAT CHAT</p>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='chat-top-page'>
    <%= link_to 'CHAT  CHAT', rooms_path, class:"product-icon" %>
  </div>
  <div class='nav-one'>
    <ul class='lists-left'>
      <li><%= link_to 'New Chat Room', new_room_path, class: "new-list" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
      <li><%= link_to 'logout', destroy_user_session_path, method: :delete, class: "logout" %></li> 
      <% else %>
      <li><%= link_to 'login', new_user_session_path, class: "login" %></li>
      <li><%= link_to 'sign-up', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to 'CHAT CHAT', root_path, class:"second-logo"%>
</header>